### ISSUE TITLE
Cannot correctly open (and therefore build) solution

### ISSUE THREAD

**Issue by redhotskull** [Elskom/Els_kom_new#190]
**Describe the bug**
I can't figure this out. I'm not a C# coder so I'm not good with this kind of stuff but no matter what I do I can't get the solution file working.

**To Reproduce**
1. Clone repository
2. Open .sln file in Visual Studio 2019

**Expected behavior**
The .sln file opens fine and is able to be built

**Screenshots**
![image](https://user-images.githubusercontent.com/58334717/145638128-875473c6-17b7-4c5e-9174-7d0b76f7111b.png)
![image](https://user-images.githubusercontent.com/58334717/145638487-3511d2cd-3b47-4e30-a7d7-7d808432fadc.png)
![image](https://user-images.githubusercontent.com/58334717/145638500-a57e36e4-86c2-4d5a-b3dd-5504a3994046.png)
![image](https://user-images.githubusercontent.com/58334717/145638513-f4ea1bd8-c675-4d49-9207-ded13bc1c050.png)

**Desktop:**
 - OS: Windows
 - OS Arch: x64
 - OS Label Version: 10
 - OS Edition: Education
 - OS Build: 19041.1348
 - Version: 2004

**Additional context**
I've gone over the other issues and discussions and tried what's in them but it just doesn't work no matter what I do. I don't know if I'm missing a component or not, I'm so lost.

**Comment by AraHaan** [comment]
The current recommended steps is to run ``dotnet tool restore`` then ``dotnet elskom-check install`` but I recommend cloning https://github.com/Elskom/runtime and then ``dotnet build -c Release`` that then go in and run the exe installers (x86 and x64) in ``artifacts\packages\Release\Shipping\`` before running that tool.

Note: If you are using arm64 you might need to install the arm64 in place of the x64 one version.

After that the solution *should* now properly open. Sorry for the delay on pushing the bits I done locally as I was setting all of the workload stuff up to work properly (as well as migrate the interop stuff to TerraFX).

**Comment by redhotskull** [comment]
Yeah no problem on the wait time, I haven't been busy lol.
Okay, first I tried cloning Elskom/runtime but it gave me a weird error with `dotnet build -c Release` so I just went to `dotnet tool restore` -> `dotnet elskom-check install`, which all worked and I was able to open and build the solution fine. 
I then tried to run the program and it tells me this.

![image](https://user-images.githubusercontent.com/58334717/147306644-a6aa5333-d8cb-4742-af64-9305485c8d88.png)

I hit yes and as soon as I do that the program ends. I went and installed .NET, both x64 and x86, but I'm still getting that error. I've tried rebuilding a couple times now, but nothing new happens. In another topic you mentioned dragging and dropping .kom files into the application, which I also tried but it still pulls up the .NET error.
Also if you want me to close this issue and reopen a new one with the built program not functioning as intended error that's fine.

**Comment by AraHaan** [comment]
I see that on my end and I am currently trying to diagnose why the problem occurs.

**Comment by AraHaan** [comment]
Mt only thought is that the issue is how my Sdk references the AspNetCore.App framework.

https://github.com/Elskom/Sdk/pull/257/files#

**Comment by AraHaan** [comment]
As for drag and drop that is currently not supported, the way it unpacks koms is by placing them in a folder named ``koms`` and then hitting ``Unpack`` which will then mass unpack kom files.

**Comment by AraHaan** [comment]
My thoughts on the issue we both see is that the AppHost might not like that I am referencing the ASP.NET Core runtime with the WindowsDesktop Runtime at the same time.

![image](https://user-images.githubusercontent.com/15173749/147316684-c257c9e1-625d-40f6-a6e8-dffa9d4345b1.png)

**Comment by AraHaan** [comment]
![image](https://user-images.githubusercontent.com/15173749/147337570-ab264b8d-ab40-4542-a97d-d50631513bdd.png)

**Comment by AraHaan** [comment]
Turns out the issue was that the program was referencing the AspNetCore runtime and that the apphost did not like it one bit.

**Comment by redhotskull** [comment]
I tried building again and got this error. This was the only one though, so I'm assuming it's a quick fix?

source\repos\Els_kom_new\Els_kom\FormsApplication.cs(28,45,28,49): error CS1503: Argument 1: cannot convert from 'System.ReadOnlySpan<string>' to 'string[]'

**Comment by AraHaan** [comment]
Yes, that is due to an update to elskom/runtime that fixes it. In order to fix it, you will need to manually clone that repository and build it from the installers branch and then run the installer.

**Comment by redhotskull** [comment]
Runtime still doesn't build properly but <dotnet elskom-check update> ran fine. Upon building I'm getting errors like this?
![image](https://user-images.githubusercontent.com/58334717/149399304-b68d4168-3c0e-460e-ac0c-183818a4e1a9.png)

**Comment by AraHaan** [comment]
Ah, that is because on the Sdk I added a thing to where the resources gets source generated so in your local clone of this repository delete the Properties/Resources.Designer.cs file.

**Comment by redhotskull** [comment]
OK! Finally built and it's running again.
It's just not unpacking any kom file I give to it. Every time I try it I get this error. 
![image](https://user-images.githubusercontent.com/58334717/149411824-251b6012-a85d-40e1-b45b-437589a99975.png)
I think the application is definitely detecting there's koms there cause it gives me an error for every kom file in the /koms folder. If it helps, these are the .kom files currently in the folder:
![image](https://user-images.githubusercontent.com/58334717/149411973-59e60992-5aab-465d-bb7d-0bc041b7c2f2.png)
I'm mostly aiming to unpack the ones dated 8/4 and 12/8, the 12/16/2020 was just to check if Els_kom would unpack them but no dice.

**Comment by AraHaan** [comment]
This is due to the fact that the program relies on plugins for the unpacking now. It used to use python but I since moved away from that as python 2.7 become end of life and it made the whole thing fragile. I could invite you to the org for the plugin code.

**Comment by redhotskull** [comment]
Yea that's no problem! I don't know how Github works so if you could DM me for it or something I'd appreciate it. Also after you invite me I'll close this issue since the program is building and it should unpack once I get that plugin.

**Comment by AraHaan** [comment]
> Yea that's no problem! I don't know how Github works so if you could DM me for it or something I'd appreciate it. Also after you invite me I'll close this issue since the program is building and it should unpack once I get that plugin.

It *should* automatically be sent to your email.

**Comment by redhotskull** [comment]
Yup I'm in. Thanks! Closing the issue now.
