### ISSUE TITLE
What's next?

### ISSUE THREAD

**Issue by Timeffect0** [Elskom/Els_kom_new#50]
## Issue Description

![build](https://user-images.githubusercontent.com/36470973/36196122-0b3769f0-11b3-11e8-87a4-eea36054625c.png)

WinStudio 2017 Vr. Korean
you look in the lower left corner is '빌드에 성공했습니다'
'빌드에 성공했습니다' -> 'complete to Build'

complete to 'Build'
What's next?

I'm confused, to see 'To Build'
Could you explain it in detail with the picture?
please

<I am not good at English.>

# Debug information
- Els_kom version: ``[Els_kom_new-master]``
- OS: ``[win 7 - 64bit]``
- OS Arch: ``[Your OS Arch here]``
- OS Build: ``[Your OS Build here]``

Note: Newer versions from time to time ship with a newer version of python embedded.

**Comment by Timeffect0** [comment]
Help me...

**Comment by AraHaan** [comment]
Sorry for late reply I have loat internet for a while so yeah.

**Comment by AraHaan** [comment]
@Timeffect0 if you would like you could contribute to the code or readme too. I hope what I explained above helps. Also I recommend using the kom-rework branch so it can not only get tested to ensure it works but for the much easeir and faster compile times.

**Comment by AraHaan** [comment]
I think I should close this for now but link it to this issue: #48.
