### ISSUE TITLE
build error win 8.1 

### ISSUE THREAD

**Issue by highlizard** [Elskom/Els_kom_new#51]
## Issue Description

[image](https://i.imgur.com/FUwCWS9.png)
![GitHub Logo](https://i.imgur.com/FUwCWS9.png)

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "echo F|xcopy /Y /c C:\Users\Noo\Documents\Els_kom_new-master\PCbuild\..\etc\pyconfig.h C:\Users\Noo\Documents\Els_kom_new-master\PCbuild\..\externals\cpython\Include\pyconfig.h
C:\Users\Noo\Documents\Els_kom_new-master\PCbuild\..\bin\x86\Release\\_freeze_pyeimport C:\Users\Noo\Documents\Els_kom_new-master\PCbuild\..\Tools\pyeimport.py C:\Users\Noo\Documents\Els_kom_new-master\PCbuild\..\PC\pyeimport.h pyeimport

:VCEnd" exited with code 9009.	komextract_new	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	123	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'io.h': No such file or directory	_freeze_pyeimport	c:\users\noo\documents\els_kom_new-master\externals\cpython\include\pyconfig.h	59	

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "echo F|xcopy /Y /c C:\Users\Noo\Documents\Els_kom_new-master\PCbuild\..\etc\pyconfig.h C:\Users\Noo\Documents\Els_kom_new-master\PCbuild\..\externals\cpython\Include\pyconfig.h
C:\Users\Noo\Documents\Els_kom_new-master\PCbuild\..\bin\x86\Release\\_freeze_pyeimport C:\Users\Noo\Documents\Els_kom_new-master\PCbuild\..\Tools\pyeimport.py C:\Users\Noo\Documents\Els_kom_new-master\PCbuild\..\PC\pyeimport.h pyeimport

:VCEnd" exited with code 9009.	kompact_new	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	123	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'ctype.h': No such file or directory	Els_kom	c:\program files (x86)\windows kits\8.1\include\um\winnt.h	31	

# Debug information
- Els_kom version: ``[your version here]``
- OS: ``[Win 8.1]``
- OS Arch: ``[Your OS Arch here]``
- OS Build: ``[Your OS Build here]``

Note: Newer versions from time to time ship with a newer version of python embedded.

**Comment by AraHaan** [comment]
That is common with using cpython api and code on branch master. Because of that I changed to full c# in branch kom-rewrite. However I currently lack some implementations for kom v3 and v4 packing.

Also in v1.5.0.0 I might change the v3 and v4 packers as well to call a encryption plugin that would handle algorithm 2 & 3 and maybe save the crc.xml in the folder to monkey patch when packing so the packer can tell which files should be packed to which algorithm.

See #48. Also if you want you can comtribute at any time. I don’t care much.

**Comment by CatGirlsAreLife** [comment]
Back filling all projects and issues to the newly created project to better sort the issues/pull requests to all the repositories on this organization.
