### ISSUE TITLE
High CPU usage when running test mods / launcher options.

### ISSUE THREAD

**Issue by CatGirlsAreLife** [Elskom/Els_kom_new#70]
**Describe the bug**

I think this is due to reading the settings while doing to packing, unpacking, testing mods, and the updating functionality.

**To Reproduce**

**Expected behavior**
Hardly any cpu usage other than the usage when packing or unpacking.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows, linux, mac] Windows
 - OS Arch: [e.g. x86, x64] x64
 - OS Label Version: [e.g. 7, 8, 8.1, 10, 17.04] 7
 - OS Edition: [e.g. Starter, Home, Professional, Enterprise, Ultimate, None] Ultimate
 - OS Build: [e.g. 7601] 7601
 - Version [e.g. 1.4.9.8] 1.4.9.8

**Additional context**

**Comment by AraHaan** [comment]
It is probably due to some of the threads orsomething.

**Comment by CatGirlsAreLife** [comment]
I think this is because of the 'while (true)' parts of the code and probably should be in a timer instead made at runtime.
