### ISSUE TITLE
Use a single version for the plugins or move them to another repository?

### ISSUE THREAD

**Issue by CatGirlsAreLife** [Elskom/Els_kom_new#85]
I think the plugins should either use the version set in the SharedVersionInfo.cs file, move them to another repository, or both.

Personally having them in a separate repository and have some sort of plugin installer which takes the url of a github repository and download the latest availible release / pre-releases might be an option. That way plugin specific code cannot be blocking releases any longer. The downside is that removing or renaming or changing function paramiters the plugins use could make the program crash because the plugin crashed (if they even can be compiled then ofc).

And then any closed sourced plugins could have their sources under externals/ or whereever where git could then ignore them from this repositiry and any possible security related code or files they may contain. As such I see this as more of a win for everyone involved.

**Comment by CatGirlsAreLife** [comment]
To be technical the plugins should probably each have their own repository and separate versions for each one and then the release links to them in some sort of source repository which can then be added on Els_kom settings to look for plugins in or something. However not entirely sure on anything yet.

**Comment by twoxzi** [comment]
I think, each plugin have their own repository. in the sln,do not using the plugin. on the other way, how about MEF(Managed Extensibility Framework, https://docs.microsoft.com/en-us/dotnet/framework/mef/index ) or MAF(Managed Add-in Framework)?

**Comment by CatGirlsAreLife** [comment]
Ye, I think my plugin loader uses MEF but not sure as it uses Reflection to load the plugins and their PDB’s from a zip file (if in a zip file) or just the plugin assembly from the Plugins folder. My plan was like this:

Each plugins a repository named by the plugin’s name, it’s own 1 project solution file of the same repository name, then added to a json file in a plugin source repository which then is read in the plugins installer form/window for installing or updating plugins. Not sure if I should check for updates by version or by checksum though. That form/window is sorta holding me up where I currently got to clone the plugins repository that I would like to make the source repository holding a json file for the current plugins there to Els_kom (linking directly to a release build that is setup exactly like how this is setup on release deployments). The only issue though then is that upon new release, I got to modify my CI currently to modify that json file according to that release, then commit and pull request it over. And if I setup the deployments to the plugins to the same repository, it would get caught in a infinite loop on tagging and releasing so :thinking:.

**Comment by CatGirlsAreLife** [comment]
The changes needed for #87 will change the current layout on this repository when the actual form comes.
